---
- name: Install Audit Pre Reqs - RedHat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ redhat_packages }}"
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }}"

- name: Install Audit Packages - Debian
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ debian_packages }}"
  when: "ansible_os_family | lower == 'debian' and {{ enable_audit }}"

- name: create audit-directory if it does not exist
  file: path='/etc/audit' owner=root group=root mode=0755 state=directory

- name: create auditd configuration
  template: src='auditd.j2' dest='/etc/audit/auditd.conf' owner=root group=root mode=0440

- name: create rules-directory if it does not exist
  file: path='/etc/audit/rules' owner=root group=root mode=0755 state=directory
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version < '7'"

- name: create rules-directory if it does not exist
  file: path='/etc/audit/rules.d' owner=root group=root mode=0755 state=directory
  when: "ansible_os_family | lower == 'debian' and {{ enable_audit }}"

- name: create sane rules
  template: src='audit.rules.redhat.j2' dest='/etc/audit/rules/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version < '7'"

- name: create sane rules
  template: src='audit.rules.redhat.j2' dest='/etc/audit/rules.d/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version >= '7'"

- name: create sane rules
  template: src='audit.rules.debian.j2' dest='/etc/audit/rules.d/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'debian' and {{ enable_audit }}"

- name: get audit.rules stat
  stat: path=/etc/audit/audit.rules
  register: audit_rules_stat

- name: remove any audit.rules file if present by OS
  file: dest=/etc/audit/audit.rules state=absent
  when: "not {{ audit_rules_stat.stat.islnk }}"

- name: create audit simlink
  file: src=/etc/audit/rules.d/audit.rules dest=/etc/audit/audit.rules owner=root group=root state=link

- name: Make sure auditd server is running
  service:
    name: auditd
    state: started
    enabled: yes
  tags: usb
